# This workflow will build and push a new container image to Amazon ECR,
# and then will deploy a new task definition to Amazon ECS, when there is a push to the "master" branch.
# githu workflow
name: Deploy to Amazon ec2

on:
  push:
      branches: [ master ]
  pull_request:
      branches: [ master ]

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'
          
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build --if-present
      - name: Test
        run: npm run test --if-present

  Deploy:
      runs-on: ubuntu-latest
      needs: build
      steps:
      - name: SSH to ec2
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: ${{ secrets.SSH_PORT }}
            script: |
                  cd /home/ubuntu
                  git clone https://github.com/rajeshreddy-T/git-workflow-test-with-node-and-ec2.git
                  cd NodeAPP_v1
                  npm install
                  pm2 start index.js --name nodeapp --watch
                  pm2 save
                  pm2 startup
                  pm2 status
                  pm2 logs

                


